apiVersion: v1
kind: Service
metadata:
  name: kubepulse-backend
  namespace: kubepulse
  labels:
    app: kubepulse-backend
    app.kubernetes.io/name: kubepulse
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app: kubepulse-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
